### ISSUE TITLE
Missing CAD Files?

### ISSUE THREAD

**Issue by turpinator** [seemecnc/Rostock-MAX-v3#1]
Id like to make a top mounted fan shroud/tunnel to direct the air more towards the nozzle for better bridging, yet... A large majority of the CAD files seem to be missing.   Sure, I could design it without them, but it would take significantly more time.
Can the missing files be added to the repo, or directed to another repo where they can be found?
(SLDW format preferred, but IGES would be fine too)

Missing top level file list:
[https://gist.github.com/turpinator/66269c6766c12a5415e60d5c3ea3323d](url)

**Comment by jjjohnson4112** [comment]
turpinator, sorry you can't find the files you are looking for. They aren't actually missing though, they just are not all in this repo. The parts you are looking for (I believe) are in the [machine elements](https://github.com/seemecnc/Machine_Elements) repository

**Comment by turpinator** [comment]
Thanks,  Found them from someone on the forums.   A link or references in the readme.md would be appreciated, as I did not see the Machine elements repo when browsing through.
